name = "mediumbackend"
main = "src/index.ts"
compatibility_date = "2024-10-12"
compatibility_flags = [ "nodejs_compat" ]
# Environment variables declared in this file are automatically made available to Prisma.
# See the documentation for more detail: https://pris.ly/d/prisma-schema#accessing-environment-variables-from-the-schema

# Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server, MongoDB and CockroachDB.
# See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTRlZjJmMzMtZTdiMS00NThhLWEyMmMtNDAxOTRkZDI3OWJhIiwidGVuYW50X2lkIjoiNGYyZGE4NmU5MzM1NmJlNGM3N2NiMWIxZjQyZjBlNGViNTA4YWIwYmRlNGFjMTBkMDNmNWVhZWI3OTYzMGZkNSIsImludGVybmFsX3NlY3JldCI6IjY4MzNmYjQ3LWEzYTUtNDNjZS04MmM0LWU2NTVlZjI5Mjg0MiJ9.8qtWzZ6aMTxMI_ivloa2YlQZYPwkjc8hnx2H6VMJxRM"
JWT_SECRET = "prod_jwt_secret"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1